CREATE DATABASE IF NOT EXISTS dash CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'dash' IDENTIFIED BY 'dash';
GRANT ALL ON *.* TO dash@'%' IDENTIFIED BY 'dash' WITH GRANT OPTION;

FLUSH PRIVILEGES;
